### ISSUE TITLE
Is this up to date?

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-typescript#20]
Just reading the book now... and came here to check out the repo / start playing... though I see the last update was from 2016 whereas the main sodium repo is far more recent

Is that because it's just stable and working perfectly so there's nothing to do - or it's out of date / neglected? :)

**Comment by the-real-blackh** [comment]
The typescript version should be stable and working perfectly. I don't think many people are using it yet, but it is 100% implemented and tested. If you encounter any difficulties I'm happy to help, and bugs I am keen to fix.

**Comment by dakom** [comment]
> The typescript version should be stable and working perfectly

Awesome, thanks for confirming!

> I don't think many people are using it yet

What?!? I'm new to this whole world, coming to JS/TS from Unity, Flash, etc. (Go on the backend and C as kid, PHP somewhere in between) - and the transition from vanilla JS to Typescript was lovely (basically writing c#) - then this past week some colleagues turned me on to "functional JS" as well as "declarative programming". As you can imagine I'm sortof taking a leap of faith here that it's worth changing my brain - but from learning up ("dr boolean", "funfunfunction", etc.) I'm _starting_ to see the benefits :D

Writing all that above in the hope that some of the millions of other programmers who share that sort of background and, hopefully, land here will empathize

Given that these approaches have such high esteem in the JS community - e.g. from Kyle Simpson (who wrote the You Don't Know JS series and is now putting together a book on "Functional Light JS") - and the extreme popularity of React or even RxJS - _**how in the world is true frp in js not more popular?!**_

Is there some massive performance hit I'm not aware of (in the context of browser-based game things... not talking about like AAA console games)? Is there some major gotcha that's preventing people from going this route?

I'm only on chapter 3 of your book now - so maybe I'm missing something... but is it just a marketing issue? It seems to me that for people coming to JS, even those who simply don't like React for various non-critical reasons (e.g. doing more game-based stuff where it's not even a great fit superficially), sodium should be a far more popular consideration, no?! Especially considering the culture of the JS community which is extremely fluid when it comes to trying out new libraries and frameworks and things.

**Comment by the-real-blackh** [comment]
Hi Dakom,

I discovered functional programming in 2007 and it turned my programming life on its head. I learned that I had been doing it wrong all these years. It was like learning programming all over again. Apart from blowing your mind, there is a real benefit: fewer bugs.

There are several reasons why the situation is as it is now. You might call Sodium and my book the "second wave" of FRP.

The first wave was Rx the *many* similar systems. Basically people saw a good idea, and put it directly to use, but in the process important parts of it - the bits to do with compositionality - got lost. There are a couple of reasons for this:
1. An FRP system is devilishly difficult to implement even though it's only 2000 lines of code.
2. The spirit of functional programming that in the original FRP got lost, because the implementors weren't seriously into functional programming.

So I spent several years implementing a "proper" FRP system. There wasn't even a production-ready FRP system in Haskell in those days, the language where FRP comes from. So I was one of the first to get "true FRP" and make it practical - meaning, make a library that could be used for production code. At this point, Rx existed and was already popular.

Then I got the offer to write a book, which took me 18 months or so. I'd already spent a few years developing Sodium. This was mostly single-handed (apart from assistance from my co-author Anthony Jones). The book writing also allowed Sodium's design to be perfected. By the end of the book writing, I was seriously out of puff. That's why the tutorials are not there. I have focused on getting ports to as many languages as possible over some of the basics.

So, yes, it's a marketing issue, but it's also a timing issue. Sodium has a much better design than Rx, but it's still very new. The book is the only means of marketing I have at the moment. I wish I could have written the book with Typescript examples, but this wasn't possible at the time due to a technical challenge that I hadn't overcome at the time.

So I hope that goes some way to explaining it. We'll get there, but for most of it, there has only been one of me.


Steve

**Comment by dakom** [comment]
I'm speechless... wow! Thank you for all your effort and hard work!!!

**Comment by graforlock** [comment]
I can assure it is working :) Check for example https://github.com/graforlock/reactive-drawing-pad

Apologise in advance from not TDDing the code, was too lazy.

**Comment by dakom** [comment]
Niice! Great example to look at, and I love the code formatting too :)
