### ISSUE TITLE
Updating cell that was created via stream.hold()

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-typescript#23]
Another newbie question ;)

In the following code - why doesn't cell.sample() value change? I thought creating a cell from stream.hold() makes that cell update whenever the stream fires a new event?

output is like:

1497987742704 0
1497987743704 0
1497987744691 0

```
Transaction.run((): void => {
    let stream = new StreamSink<number>();
    let cell = stream.hold(0);

    stream.listen(n => {
        console.log(n, cell.sample());
    });

    setInterval(() => stream.send(Date.now()), 1000);
});
```

**Comment by dakom** [comment]
For comparison, this does work (e.g. the cell is getting updated somehow... just doesn't come through via sample?

```
Transaction.run((): void => {
    let stream = new StreamSink<number>();
    let cell = stream.hold(0);

    stream.snapshot(cell, (a, b) => b)
        .listen(console.log);
    
    setInterval(() => stream.send(Date.now()), 1000);
});
```

**Comment by graforlock** [comment]
Primitives in Sodium are immutable; meaning that they return new instance on each operation. When you convert stream to a Cell you get a new Cell, and not any kind of reference to a stream.

The second example is, therefore correct. Its what you want to do most of the times. You can also use lift, but you'd have to map it from side effect typically, like event listener callback.

**Comment by the-real-blackh** [comment]
@dakom, the function passed to listen() should not use any FRP at all. That is, you should never call sample() from that function. All that function should do is to do something with the output value.

**Comment by the-real-blackh** [comment]
@dakom, actually I've just realized why it's happening. If you use snapshot to get the value of the cell, then Sodium can track the dependency, and it knows the cell is alive. If you use sample(), then it can't. Because the cell isn't alive, it doesn't get updated. This is all to do with the memory management. (Sodium is likely to be the only FRP system for Javascript that never leaks memory.)

**Comment by dakom** [comment]
Thanks for the insight! It would help - maybe on the typescript Readme, to highlight some of these requirements (no frp within listen(), sample() doesn't "count" as frp, etc.)

Or, alternatively, maybe a longer explanation of what exactly counts as a dependency?

**Comment by the-real-blackh** [comment]
My aim is to put all of this stuff into the API docs. Most of that in Typescript is copied over from the Java version. I just added this text to the Typescript version of Cell::sample()

NOTE: In the Java and other versions of Sodium, using sample() inside map(), filter() and
merge() is encouraged. In the Javascript/Typescript version, not so much, for the
following reason: The memory management is different in the Javascript version, and this
requires us to track all dependencies. In order for the use of sample() inside
a closure to be correct, the cell that was sample()d inside the closure would have to be
declared explicitly using the helpers lambda1(), lambda2(), etc. Because this is
something that can be got wrong, we don't encourage this kind of use of sample() in
Javascript. Better and simpler to use snapshot().

**Comment by dakom** [comment]
@graforlock - you're right on the money! I'm coming to this right as I'm also just learning about fp in general, so I'm still just absorbing how a functor works and things like that :)

It's not entirely clear how a Cell relates to a functor or how listen() might relate to lift(). From a newbie perspective - it seems like snapshot is returning a single Cell object rather than returning new immutable copies whenever the call changes?

**Comment by the-real-blackh** [comment]
I added some more:

NOTE: If you need to sample() a cell, you have to make sure it's "alive" in terms of
memory management or it will ignore updates. To make a cell work correctly
with sample(), you have to ensure that it's being used. One way to guarantee this is
to register a dummy listener on the cell. It will also work to have it referenced
by something that is ultimately being listened to.

---
I think that learning FRP is an efficient way to learn the real basics of FP - the most useful part. map() is the functor operation of Cell.

I don't understand your question about snapshots.

**Comment by dakom** [comment]
Great!

I hadn't looked in the lib source before - lots of helpful comments there actually, easier than what I was doing up till now which was referencing the API section in the book :)

Just for kicks I tried going the lambda route and got something wrong in the syntax... I know this is probably a silly way to do it but just to have around, how would you use sample() within a listen() such that it doesn't get lost? This doesn't fire anything:

stream.listen(n => {
        lambda1((a:Cell<number>) => console.log(a.sample()), [cell]);
});

re: learning fp via frp. agreed! my actual goal is to write maintainable-ish code, mostly building educational apps/games... coming to the browser from Unity which uses like a component-entity-system sort of approach, it seems fp/frp is the best way to do things, so I'm just sortof absorbing as much as I can on both sides as I try to swim in the deep end ;)

**Comment by the-real-blackh** [comment]
Umm... you can't do it with listen() at all, because you're trying to do something that the library wasn't designed to do. Use snapshot instead.

**Comment by dakom** [comment]
Gotcha, was just testing you :P

kidding - it was my confusion around "In order for the use of sample() inside
a closure to be correct, the cell that was sample()d inside the closure would have to be
declared explicitly using the helpers lambda1(), lambda2(), etc"

Will open a related question on the sodium forum since it's not really an "issue"
