### ISSUE TITLE
Problem running tests in chrome

### ISSUE THREAD

**Issue by palfvin** [SodiumFRP/sodium-typescript#29]
I tried running the tests by cloning the repo and opening `sodium-typescript/examples/basic/suite.html` in chrome. The first few tests passed, but most failed as this one did:
```
mergeSimultaneous - FAIL:
suite.js:43 TypeError: Sodium_1.run is not a function
    at suite.js:105
    at test (suite.js:35)
    at suite.js:102
```
Am I doing something wrong?

**Comment by the-real-blackh** [comment]
Typescript and Javascript confuse the hell out of me. I ran them in node. The only success I've had with browsers is when I use "browserify". Anyone else know?

**Comment by dakom** [comment]
All I can say is that I feel your pain. I spent like a month setting up boilerplate for my own stuff and, since it's been working, never touch the config stuff again (webpack, karma, etc.)

I remember at one point it would even only work in certain browsers (firefox, not chrome... or maybe chrome not firefox).

The javascript ecosystem is FUBAR, and not in the nice programming foobar kind of way ;)

**Comment by graforlock** [comment]
There is fuse-box and it solves all webpack boilerplate. I might have a look today if its not solved but last time I did run tests - they just worked.

**Comment by dakom** [comment]
OK, I've now migrated the project totally over to fuse-box and updated the readme.

Currently fuse-test-runner does not support browser-based tests. Personally I'd prefer to wait till they've added that instead of adding in Karma/Jest/etc. now.

Anyway - the current config does support both node-based unit tests _and_ browser-based integration tests (e.g. via `npm run dev`). I believe this would cover most needs. @palfvin feel free to clone the repo, check out the Readme, and ping me if you need further help.
