### ISSUE TITLE
Why do u use Lambda wrapper?

### ISSUE THREAD

**Issue by xgrommx** [SodiumFRP/sodium-typescript#4]
Hello @the-real-blackh 
I think it isn't necessary, because we can use just anonymous version like `(a, b) => a + b` I don't understand why u create this one https://github.com/SodiumFRP/sodium-typescript/blob/master/Lambda.ts ?

**Comment by the-real-blackh** [comment]
I'll write a blog post to explain this fully, but it's to do with the fact that there are no finalizers in Javascript. I have to find another way to manage the memory, so you have to use lambda1() and friends when you are using switch. You have to declare any sodium objects held inside the lambda. If you want to get an idea of what I mean, run the test cases, and then in test case "switchC", change this line:

        csw = csw_str.map(lambda1(s => s == "ca" ? ca : cb, [ca, cb])),

to this

        csw = csw_str.map(s => s == "ca" ? ca : cb),

you'll see that it doesn't work. Actually it should throw an exception instead of giving the wrong answer. I'll work on that.

**Comment by the-real-blackh** [comment]
See https://github.com/SodiumFRP/sodium/issues/85

**Comment by paldepind** [comment]
> I'll write a blog post to explain this fully, but it's to do with the fact that there are no finalizers in Javascript.

Sounds exciting. Automatic memory management for a pure FRP library (is the TS version pure?) without weak references is challenging.
