### ISSUE TITLE
v1.0.7 doesn't seem to work with webpack

### ISSUE THREAD

**Issue by Ziriax** [SodiumFRP/sodium-typescript#41]
I had to install v1.0.4, otherwise I got the webpack error:

```Critical dependency: require function is used in a way in which dependencies cannot be statically extracted```

And the webpack loader couldn't find sodiumjs when running

**Comment by dakom** [comment]
Can you share a temporary repo to reproduce?

**Comment by Ziriax** [comment]
Will do so, give me a couple of days

**Comment by Ziriax** [comment]
I tried in 3 different existing webpack projects, and it always fails.

I will update a minimal example soon.

**Comment by dakom** [comment]
Thanks - it's very likely something wonky in the fuse-box config, hopefully it won't be a big deal to fix :)

**Comment by Diaaz** [comment]
I am having the same problem with a new Angular CLI project (ng new PROJECT-NAME). Reverting to 1.0.4 'solved' the problem.

**Comment by dakom** [comment]
I've had some problems with FuseBox on an unrelated project too... I'll change Sodium to use rollup instead, feel free to ping me on that if it's not done in a day or two :)

**Comment by huanhulan** [comment]
same thing happens to me too...and the typescript report that can't find .d.ts file of sodium.

**Comment by huanhulan** [comment]
the problem has been solved by add
```javascript
module.unknownContextCritical: false,
```
but another problem occured /(ㄒoㄒ)/~~:
```
Uncaught Error: Cannot find module "."
    at webpackMissingModule (sodium.min.js:1)
    at Object.<anonymous> (sodium.min.js:1)
    at Object../node_modules/sodiumjs/dist/sodium.min.js (bundle.js:8571)
    at __webpack_require__ (bootstrap 1cc0a4e9a2d25ac69f6a:659)
    at fn (bootstrap 1cc0a4e9a2d25ac69f6a:85)
    at Object../app/main.ts (main.ts:4)
    at __webpack_require__ (bootstrap 1cc0a4e9a2d25ac69f6a:659)
    at fn (bootstrap 1cc0a4e9a2d25ac69f6a:85)
    at Object../app/index.ts (index.ts:4)
    at __webpack_require__ (bootstrap 1cc0a4e9a2d25ac69f6a:659)
```

**Comment by dakom** [comment]
oh wow I completely forgot about this... will try to port tonight, sorry about the delay!

**Comment by huanhulan** [comment]
@dakom I have fall back to version 1.0.1 to avoid the headache. Looking forward your good news: )

**Comment by dakom** [comment]
1.0.8 now live on npm, and tested against a local webpack project (with awesome-typescript-loader).

Everything should be fixed now for webpack, let me know how it goes :)

Along with updating packages and things, I set the rollup build to strip the external dependencies, which brought the bundle size down by half!

note: I wasn't able to test The UMD/Browser style since that requires also importing typescript-collections and sanctuary-type-classes into globals, and I couldn't get that to work with typescript-collections yet, but it is _there_ so hopefully it works ;)

Also, I'm unfamiliar with Bower... from past discussions it seems that it just needs the `dist` folder checked in, which it is, so I'm hoping that just works too, hehe.
