### ISSUE TITLE
Sinks without listeners?

### ISSUE THREAD

**Issue by Ziriax** [SodiumFRP/sodium-typescript#45]
It seems that it is impossible to send a value to a sink, if nobody is listening to it. 

Doing so results in the exception `send() was invoked before listeners were registered`.

What is the reason for throwing this exception? Shouldn't the value just be ignored, just like with events that have no event handlers attached?

**Comment by the-real-blackh** [comment]
It's a result of the trickery needed to implement the proper memory management on Typescript. We only create the notification machinery when a listener is added. If we ignored the value instead of throwing an exception, then if there were a cell that held the value, then it would not be changed by the sent value. So, an exception is better than unexplained weird behaviour.

**Comment by dakom** [comment]
I copied the text here and edited it slightly over on the wiki: https://github.com/SodiumFRP/sodium-typescript/wiki/Send-without-listeners

**Comment by cubuspl42** [comment]
This doesn't seem to work for `CellSink`:

```typescript
const sink = new CellSink(1);
sink.send(2);
console.log(`sink.sample() = ${sink.sample()}`);
```
The snippet above prints "1" without any exception.

**Comment by clinuxrulz** [comment]
Will reopen for a bit. Your right. CellSink probably should through an exception too, just like StreamSink.

**Comment by the-real-blackh** [comment]
For memory management reasons on Javascript, CellSink won't process send()s properly if there are no listeners. So that's what's happening here. Ideally it would throw an exception when this happens.

If I remember correctly, we had to remove some situation of an exception being thrown, because it wasn't quite right and it broke something. So it may not be completely straightforward to get this logic right.

**Comment by clinuxrulz** [comment]
No worth the risk. Will close for now.
