### ISSUE TITLE
DiscreteCell?

### ISSUE THREAD

**Issue by Ziriax** [SodiumFRP/sodium-typescript#46]
Should `DiscreteCell` also become part of the Typescript version?

**Comment by the-real-blackh** [comment]
I would prefer all versions to be the same. I understand and agree with the reasons behind DiscreteCell and I considered it myself. The question is, is DiscreteCell a good idea overall? Does it create any difficulties in the API? Does it unnecessarily complicate things?
When I considered doing it, I ended up making the decision to keep things simple. But I'd be happy to re-consider that.

**Comment by clinuxrulz** [comment]
In C# Cell is just like Lazy capability wise. It would feel like code repetition divide Cell into Cell and DiscreteCell. Plus it might annoy existing users of the library when they update.

**Comment by the-real-blackh** [comment]
The difference between Cell and DiscreteCell is that updates() and value() are not available on Cell. The point of the distinction is to enforce the nice semantic property of non-detectability of changes in the cell's value, but still allow you to have special discrete cells that don't have that property.

**Comment by clinuxrulz** [comment]
And listen() not available on cell. It might be hard to convince an end-user what he/she is gaining capability wise.

**Comment by jam40jeff** [comment]
I agree that all versions should be kept in sync as closely as possible.  That being said, the C# version currently has a different public API in a couple of ways.

(1) The addition of `Maybe<T>` and `Either<...>` types (for optional values and anonymous algebraic data types, respectively).  These are crucial types to have to implement proper type-safe functional code.  Some languages already have these types (for instance F#) and should simply use the types appropriate for that language.  Languages that do not have these types should in my opinion have them in the Sodium library.  Some languages are tricky (Java) because although they have a "Maybe-ish" type (`Optional<T>`), it is widely considered "broken", providing little reason to use it over a properly implemented optional type.

(2) The addition of the `DiscreteCell<T>` type.  This is a new addition which is meant to augment the original `Cell<T>` type.  Whereas `Cell<T>` should be assumed to be continuous (non-detectability of cell steps), `DiscreteCell<T>` is a specialized version of `Cell<T>` which has been created in a manner such that it is known to exhibit discrete behavior.  In my opinion, this is a desirable type to have.  Many LOB applications will nearly exclusively use this type.  It removes the need for the `Operational` members and does not change any of the semantics of Sodium.  It can be thought of simply as a regular `Cell<T>` plus the `Stream<T>` which is the only manner of updating the value of the cell.  It was actually created because I found many real-world cases where I had to carry around both a `Cell<T>` and the `Stream<T>` which I had used to create it (through `Stream<T>.Hold(T)`).  `DiscreteCell<T>` is simply a formalism of this practice.  Thus, when creating a cell, if a continuous cell is being created, only the `Cell<T>` type may be used.  However, if it is known at the time of the creation of the cell that it will be discrete, then a `DiscreteCell<T>` should be used.  This can be seen in the examples, with the Continuous Time example using a regular `Cell<T>`, while many other examples use `DiscreteCell<T>`s.  Another advantage of adding the `DiscreteCell<T>` type is that it allows moving a few members off `Cell<T>` which had no meaning for a truly continuous cell and onto `DiscreteCell<T>` (such as `Listen`).  This actually cleans up the API for continuous cells.  Thus, although it does add a new type, I believe that overall it actually makes the API cleaner by removing the need for the `Operational` class and by removing members from `Cell<T>` which assume the underlying cell is discrete.

**Comment by jam40jeff** [comment]
@clinuxrulz Technically, `Listen` should not be available on cells at all (without `DiscreteCell<T>` being present), since we shouldn't be able to detect cell steps.  The only way to extract the value of a continuous cell should be through `Sample`.

One thing I also should have mentioned in my above comment is that `DiscreteCell<T>` is a superset of `Cell<T>`.  It's technically not a subclass of `Cell<T>`, but it contains a property to access the underlying `Cell<T>`.  Thus, a `DiscreteCell<T>` can do everything a `Cell<T>` can do, plus more.  It is desirable to use in any case where it is possible to use it.  There is no advantage to treating a known discrete cell as only a `Cell<T>`.

**Comment by the-real-blackh** [comment]
@clinuxrulz 
That question is not simple. I think listen() probably should be available on Cell.
That's why I'd be happy to add it as long as everything is very carefully considered. Also, I don't like long names.

@jam40jeff 
I agree with (1), though I didn't do that in the Typescript version. Maybe you're right and I should add this. I don't think the different versions should be exactly identical. Making the library idiomatic to the language should take precedence.
(2) I'm definitely happy to consider this for all languages - and would prefer them all to be the same in the long run, but I would like to be very fussy about how it's done.

**Comment by jam40jeff** [comment]
@the-real-blackh Per `Listen` being available on `Cell<T>`, I would disagree.  At best (if `DiscreteCell<T>` doesn't end up making the cut), I would think it should only be available in `Operational`.

Per #1: Yes, and the F# version does not have `Maybe<T>` or `Either<...>` types in Sodium because the language already provides appropriate constructs for these two concepts (`optional` and discriminated unions).

Per #2: I completely understand.  I appreciate your fussiness as I tend to be the same way (and it's actually one of the things that attracted me to the library in the first place).  I would be happy to discuss my implementation of `DiscreteCell<T>` in the C# library in more detail at some point and would love to get your feedback.

**Comment by clinuxrulz** [comment]
@jam40jeff , @the-real-blackh thank you for your long explanations. Does it really eliminate the need for ```Operational``` ? What about ```split```. If so, I'd be happy to make that change in the Rust version, before it is finished.

**Comment by jam40jeff** [comment]
@clinuxrulz I thought about mentioning that, but my post was already getting too long. :)  But, yes, you're right.  `Operational.Split` is the only item still necessary (`Operational.Defer` is simply a specialized case of `Operational.Split`).  I did leave `Operational.Updates` and `Operational.Values` in place for backwards compatibility, but if you are using `DiscreteCell<T>`, there is no reason to use them.

In the long run, my hope would be that we would find the use cases for `Operational.Split` (my gut says there aren't too many...I have only found one so far through pretty extensive use of the library) and formalize those into proper (non-operational) methods which wrap the split logic, rather than exposing it for general usage.

**Comment by the-real-blackh** [comment]
Argument in favour of Cell having listen():
When you use listen() you are in the operational world. Not polluting the FRP world with bad semantics is the only aim, and listen() doesn't do this.
A common use case is animation. You want the cells to be continuous in the animation logic, and you want them to be discrete in the real world, because they need to be, or the code can't be implemented. Requiring animations to be written using DiscreteCell() because otherwise they can't be rendered defeats the purpose of Cell altogether.

**Comment by jam40jeff** [comment]
@the-real-blackh I may not be following your example properly, but I thought the only proper way to rasterize a continuous cell was through `Sample()`.  `Listen` forces the hand of the underlying `Cell<T>` implementation to be discrete and may be limiting if other ways are sought after (theoretically) to implement continuous behavior in `Cell<T>` in the future.

**Comment by the-real-blackh** [comment]
@jam40jeff Yes, it does force the underlying cell implementation to be discrete, but a clever implementation should be able to optimize this. This is basically what push-pull style implementations do. I don't agree that it's a good idea to treat Cell as continuous from an operational point of view. That severely and unnecessarily limits the usefulness of Cell just so the developer of the library can be lazy.

**Comment by jam40jeff** [comment]
@the-real-blackh If a cell is semantically continuous, wouldn't it be a bad thing to expose the discreteness of the implementation?  For example, in continuous time, you achieve the appearance of a continuous cell by pushing time into the FRP world at discrete intervals.  Thus, the example *could* be implemented using `DiscreteCell<T>` and `Listen` rather than `Sample`, but I believe this would be wrong.  This would mean that all listeners would have to rasterize the cell at the same rate.  Let's say you're pushing time into the FRP world every 1/60th of a second, but we have two operational consumers of the FRP logic which wish to sample at different rates, one at 1/60th second and the other at 1/30th second.  With `Listen` they would have to have knowledge of the input frame rate, and skip `Listen` calls accordingly.  With `Sample` they would simply sample the cell at the rate they choose because it has the semantics of being continuous.

I guess I just don't see the advantage of being able to `Listen` on a continuous cell.  If we have a known discrete cell, then we can use `DiscreteCell<T>` and gain a `Listen` method.  If we have only a `Cell<T>`, the creator of that cell is specifying their intent for it to be have continuous behavior and `Listen` has no semantic meaning.  If we are worried about wasting CPU cycles due to sampling continuous data that doesn't change very often, we can have our `Sample` call compare to the last sampled value and do nothing if it hasn't changed.  But at least we don't have to make assumptions about the underlying implementation or the rate of data being fed through the opposite end of the operational spectrum to gain the desired behavior.

**Comment by clinuxrulz** [comment]
There is a lot I want to say, but I'm stuck on a mobile phone and have to go soon. You could visualize sFrameTick as when the monitor is ready  to render and sample your cDisplay (with is continuous) . CPUs are discrete by nature, no escaping that.

**Comment by Ziriax** [comment]
Do you guys have actual practical examples of the advantages of having continuous cells? As far as I understand a Behaviour in the original design was a time continuous signal, and is that useful as a basic building block?

E.g. if you want to sample a continuous signal without loss, you must sample it at the Nyquist rate... But you don't know that rate unless you expose it... And that defeats the purpose, since then the change frequency of the cell is detectable...

Wouldn't a continuous signal be better represented by a discrete cell of piecewise continuous functions over time, like the example in Stephen's book that uses parabola to model Newtonian physics? Would that example fail miserably if a discrete cell was used? 

Also, in practice, when you have (the illusion of) continuous user input, does such a "continuous" approach even work? How would one model the mouse position? If we want this to be continuous, we have to do some prediction, or curve fitting. Device drivers sample a mouse at a very high frequency, but ideally a mouse signal is approximated by some piecewise curves, and the signal is then a cell of these curves. 

Just brainstorming here, I never had the time nor skills to dig deep in the foundations of FRP...

**Comment by clinuxrulz** [comment]
@Ziriax I think you onto something there. The current sodium implementations work fine in practice. Maybe even trying to support a fully continuous Cells is absolute overkill. Having mouse-move as a Cell rather than a DiscreteCell would complicate something as simple as Drag and Drop which highlights components when the mouse hovers over them, especially when connecting to an existing GUI framework such as Swing.

I will have to read up on Conal Elliott's Push-Pull FRP paper to get a feel for any advantages.

**Comment by Ziriax** [comment]
Conal wanted to write stuff like `map cos time` and `integral velocity`. In theory and semantically these are just continuous functions that can be evaluated at any time, at random,  but to make a practical FRP system, you cannot implement like this.  

But even if `time` is a step function, one would still be able to write the formula's above. 

The main advantage I could see, is that by hiding the discrete nature of a cell, you can write code that can be both push based and pull based. But then cell should not have a listen function either. 

For example `map cos time` is much more efficient to evaluate pull based. So potentially large parts of a dataflow graph could be evaluated using pull. 

So it seems I just answered my own question, lol. Yes, continuous cells can be useful if one day parts of the dataflow graph will be evaluated pull based?



I am just curious to see what one gains by hiding the discrete nature of a signal.

**Comment by Ziriax** [comment]
Well, as far as I understand, in pull based dataflow systems, you can classify signal functions as constant, "pure" aka stateless aka history-independent, and statefull aka history-dependent. 

Constant and pure signal functions can be evaluated at any time, but statefull SFs can't. For example, `map cos time` would be pure, but `integral velocity` is typically statefull, since it accumulates a sum, you can't have random access by time.

Therefore `Time -> a` is not restrictive enough. You really only want to be able to sample at the `current time` to be efficient. Conal actually used `future values` eg promises, and insanely clever trickery with time, to avoid glitches. Actually Alan Jeffrey recently implement a first order FRP system in JavaScript using just Promises :-) I found this an interesting read: http://www.asaj.org/papers/rebls15.pdf

But if you are using pull-based evaluation with promises, you won't gain much IMO, because you end up with callbacks again.

Systems like Yampa can be heavily optimized just because they do not allow 'seeing in the future', these are simple pull based dataflow evaluation systems, that only allow one to see values 'now', and not in the past nor future. But they suffer from scalability, and push based solves that. It is intriguing, you can be fast on the small scale with pull, or efficient on a large scale with push, but combining these two, as Conal intented, remains work in progress as far as I know.

But I think we are getting off topic here ;-) Again, none of this information is very precise, I am a self-made man with an interest in FRP, but I don't have deep exact knowledge about these things, but after 30 years working as a game, graphics, animation and frontend hacker does give some 'intuition' about these things.

**Comment by jam40jeff** [comment]
If you look at Stephen's continuous time example in the repository, you can see an example of treating cells as continuous.  In the Bounce example, he simply writes an equation for the path of the ball as a Signal by integrating over gravity and velocity, then lifts this signal with the time cell.  The resulting cell gets sampled every time a frame is rendered.  This is thus pull-based and fully continuous.  He also implemented the push side (even with the timer) by allowing you to set "timers" (which seem to me like Conal's promises) which defer some work to happen at a known future time (and, yes, internally they use callbacks, although these are not exposed to the user).  It's a little hidden in the framework, being in the Time namespace, but the relevant code is available in the `TimerSystem` class.  It's a brilliant implementation in my opinion, both for what it can accomplish, and yet its simplicity.

As I converted the continuous time example to Sodium C# 2.0, what I realized is that (at least in the examples) time is the only continuous cell sink.  Thus, the only continuous cells are those which are mapped or lifted from the time cell (and thus functions of time themselves).  These are the cells which must be sampled.  Every other cell (including things like the position of the mouse, which is fed through the system discretely albeit frequently) would be treated as discrete.  I re-read Conal's paper last night and I believe this is exactly the optimization he is talking about...being able to push discrete values through the system while also having continuous values available to be pulled, all the while allowing the two types to seamless integrate with each other.

To me, having both `DiscreteCell` and `Cell` is just a formalization of Conal's specification, which allows his push/pull optimization to flow all the way to the operational output end, rather than just through the internals of the FRP logic.

After converting Stephen's samples over to Sodium C# 2.0, I also noticed that `Listen` is used heavily on the discrete cells (as it should be to avoid pull-based polling on values which only change and known times), and that `Sample` is exclusively on the continuous cells, which further reinforces my belief that `Listen` doesn't have a meaning for continuous cells.  The only place in the examples where I could see a use for `Listen` on a cell is the Zombicus example, but that example treats time as discrete, and yet still only calls `Sample` on the time cell.  It actually uses a parallel `sTick` stream to track steps in the time cell, and is why even in this example, `Listen` is not called on the cell.  In this example, time could be converted to `DiscreteCell` to take advantage of this and remove the need for the separate cell and stream.

**Comment by Ziriax** [comment]
Yes, the bouncing ball example is insanely brilliant! But it's not interactive. The example would be more interesting if it would be a pong game IMO. Nevertheless, I'm going to read the example again, and see if I can port it to Typescript.

Also, why is only `time` continuous? Can't any analog device attached to the system be treated as continuous? Because on a computer, time is not continuous. Actually using a floating point for time will result in rounding errors  when the simulation is running for a long time (although with a `double`, that would be very long time).

I would love to see a more general solution to the bouncing ball example, with e.g. fully automatic differentation. Actually Projective Geometric Algebra would be fantastic for this, since it offers fully automatic differentiation, intersections, rotors, motors, interpolation, etc, all within a single solid framework, that works the same in 2D as 3D.

But I guess we are then talking about a continuous time physics engine :-)

**Comment by jam40jeff** [comment]
I had said that time is the only *cell sink* that is continuous *in the examples*.  However, I would argue that time is the only logical *cell sink* at all now that you bring it up.  Continuous cells can model other continuous behaviors, but they are by definition functions of time and will just be created by functions lifted into the time cell.

Any inputs to a computer are discrete, just as any outputs will be (unless we can get Sodium to run on an analog computer! :) )

**Comment by dakom** [comment]
@jam40jeff - would love to see a simple pong implementation! I am toying with that idea myself too... not quite sure how to deal with timers in the web api... I'll open a separate issue for that actually.

Should we close this issue?

**Comment by dakom** [comment]
Btw - though it's buried way up there, on the topic of Maybe/Either/Optional - I would suggest _not_ introducing that into the core lib. I think I mentioned this somewhere on the forum but it's worth discussing here.

Sanctuary offers those, and due to making Sodium Fantasy-Land compatible, they can interop just fine, and it allows the user to pick any Maybe/Either/Pair/etc. implementation they like, as long as its FL-compatible.

**Comment by dakom** [comment]
Also - it's been a while since the core issue here is discussed... one thing that stands out to me in the argument is that `DiscreteCell` seems to be the more usual requirement, while `Cell` is inherently useful for its simplicity (e.g. the integrating over time example).

Would it not make sense then to give `DiscreteCell` the shorter name? e.g. `Cell` and `ContinuousCell` or something like that?

**Comment by Ziriax** [comment]
I personally like `Cell` for variables that change discretely over time, and `Signal` for a time continuous function. Short powerful names. But that's just me ;-)

**Comment by jam40jeff** [comment]
@dakom I would love to work on the pong implementation soon, but I haven't had much free time lately.  I will try to get to it when I can.  Thanks for the reminder.

@dakom I agree that `Maybe` and `Either` should not be added to the JavaScript/TypeScript library.  I was referring to ways in which the C# version differed, and I believe I mentioned that those types were meant to plug holes in the C# language/available frameworks and that they likely shouldn't be ported to other languages unless they are specifically needed for that language.

@dakom I agree that the names should be reworked, but keep in mind that `Cell` isn't to be used due to simplicity, but rather that the semantics of the cell are such that it is not discrete.  (All discrete cells are also cells, but not vice versa.  Continuous cells are regular cells that are not also discrete cells.)

@Ziriax I agree that the names could be reworked.  I actually really like the `Cell`/`Signal` suggestion and would like to implement that, but it will have to be a major release as that is a huge API change.  Sodium 3.0?  Also, `Cell` would then also be able to behave like a `Signal` (currently `DiscreteCell` can behave like `Cell`) but I would like to expose that differently.  Currently, `Cell` is a property on `DiscreteCell`, but I would like to make the new `Cell` type have a method `AsSignal()` rather than a `Signal` property.

**Comment by dakom** [comment]
@jam40jeff By the way I've also been planning to make a sodium-pong for a while... I might do it independently too then we can compare notes :)

In terms of API design - one thing to point out, is that I _think_ new API constructs need to be implemented in terms of the "denotational semantics", no? (@the-real-blackh maybe you can confirm/reject that requirement?)

Or in this case is it simply bundling the primitives together in a useful way for the end user? If it's the latter, I like the simplicity of less surface area, even if it means I need to copy/paste... we could have a "recipe" section on the wiki for common scenarios, and then it's no big deal for people to copy a "DiscreteCell" recipe into their own codebase, for example.

Just thinking out loud...

**Comment by jam40jeff** [comment]
@dakom `DiscreteCell` is simply a combination of a Cell and the Stream used to update it.  It does not violate the denotational semantics in any way.  I would not be in favor of having copy pasta for this class as I believe it should be used in most code bases, along with all of the combinators using and returning `DiscreteCell`s.

@Ziriax One issue with renaming `Cell` to `Signal` is that there is already a `Signal` class in the examples.  However, when looking at that class, I believe it is really just a specialization of `Signal` and maybe should be renamed to something like `PolynomialSignal` as it is a signal implemented as a polynomial function over time.

**Comment by dakom** [comment]
@jam40jeff I think it's fairly idiomatic with typescript/javascript to import a million libraries from npm... if DiscreteCell _can_ be expressed via a simple wrapper class with copied getters/setters, I think my vote goes toward publishing that as a separate library and then the user is free to import and use it (e.g. sodium-typescript-helpers or sodium-typescript-discrete, etc.)

I don't feel strongly about this - and it seems from the discussion above that there could be optimization paths available by either baking this in or leaving it out. Just voicing my vote that as a _user_ I'd prefer to keep the core API simple and then have this (and many more!) helper classes as a separate import.

**Comment by dakom** [comment]
Accidentally hit the close button instead of cancel, hehe ;)

The comment I was going to cancel was a point about "simple" meaning keeping the primitives in line with the core semantics and not exposing very much beyond that.

**Comment by jam40jeff** [comment]
@dakom I agree that anything which is feasible to be moved to an external library should be, but I don't feel `DiscreteCell` is a viable candidate for this if it is to be included.  `Stream.Hold` is a core function which produces a `DiscreteCell`.  The behavior of this method means the resulting cell must be discrete by definition, so if `DiscreteCell` were moved to another library, we would only have two options:

(1) Make `Stream.Hold` return `Cell` rather than `DiscreteCell` and lose the knowledge that a discrete cell was called in the first place.  The library could contain another `Hold` method (`HoldDiscrete`?), but it would have the exact same behavior except that it would return a `DiscreteCell` instance in the end.  This seems confusing and more complex without any benefit.  Given the existence of a `DiscreteCell` class, there is no reason to have a `Stream.Hold` method which does not return a `DiscreteCell`.

(2) Move `Stream.Hold` to this external library.  I am also strongly against this idea as `Stream.Hold` is the way 99.999% of cells will be created (and 100% in most applications).  It would mean that nearly every single consumer of Sodium would have to bring in the external library to get what is now a core function.

The tight coupling of `Stream.Hold` and `DiscreteCell` was actually my main motivation for including `DiscreteCell` in the core library.

I do have many addons which I use regularly with Sodium which I would like to make external libraries for, but I don't believe `DiscreteCell` should be moved out of the core library.

**Comment by jam40jeff** [comment]
@Ziriax As far as naming goes, I have again thought about it some more and feel that `Signal` may imply some extra meaning beyond what we want for the vanilla (base) class.  I am now considering `Behavior` for what is currently `Cell` and `Cell` for what is currently `DiscreteCell`.  What are your thoughts?

Since this is a pretty major API change, I don't want to do anything until there is some discussion about this and we all have time to mull it over since I would like it to be a one time change that sticks.

**Comment by Ziriax** [comment]
I never understood Conal's choice for the name 'Behavior', but maybe he had good reasons for choosing it. I will ask him personally (we were colleagues for a while). 

But it is nice to honour the original inventors with the name 'Behavior', especially since Paul Hudak, the other inventor,  passed away.

Also, since renaming 'DiscreteCell' to 'Cell' is backwards compatible I guess, I think your suggestion makes good sense.

**Comment by Ziriax** [comment]
The only other short word for 'Behavior'  that I can come up with is 'Flow', since this expresses the semantically smooth flow of values over time.

**Comment by the-real-blackh** [comment]
As I've said, I'm happy to add the notion of a non-discrete cell. My concern is that I would ideally like 1. All platforms to use the same naming. 2. The book not to be out-of-date. For those reasons I would prefer to see 'Cell' for the discrete one.

'Signal' or 'Behavior' both seem like acceptable names for the non-discrete one.

**Comment by the-real-blackh** [comment]
So, @jam40jeff, very happy with your proposal of Cell for the discrete one and Behavior for the continuous one.

**Comment by the-real-blackh** [comment]
Incidentally, the publisher didn't like the name 'Behavior' because of potential confusion with the OO meaning of the term, which I think refers to what methods do.

**Comment by dakom** [comment]
@jam40jeff - "Stream.Hold is a core function which produces a DiscreteCell", ah - that clears up it up for me, thanks!

re: naming, I like shorter words too... though I think everything's been used somehow, hehe. For example, `Signal` has some prior meaning for [event emitter type libraries](https://github.com/millermedeiros/js-signals) and it could get pretty confusing for people coming from PIXI/flash/etc. .. `Flow` is a nice word, but it doesn't quite capture the idea for me (sounds too close to Stream)... 

Fwiw, I think `Behavior` is the one to beat, even though it has some other meaning - that meaning is in a different-enough space imho and "Behavior" already has strong roots in FRP literature...

**Comment by jam40jeff** [comment]
Thanks for the feedback guys.  I will go with Cell and Behavior and make a 3.0 release of the C# library.

**Comment by dakom** [comment]
Awesome @jam40jeff !

@the-real-blackh will you make the changes for the Typescript version? I'd volunteer but I don't know how the internals work and I'm afraid I'd probably do harm than good by figuring it out "on the job" :\

**Comment by the-real-blackh** [comment]
@dakom no worries

**Comment by jam40jeff** [comment]
This will be implemented as part of #56.

**Comment by dakom** [comment]
Just to mention, coming back to read this issue having gained a bit more familiarity with the library (and implementing a pong which is pretty much based on `DiscreteCell (Time -> a)`, there's a treasure trove of information here!

Really good stuff I didn't understand on first read (and still don't understand completely). Thanks all!
