### ISSUE TITLE
Stream.filterOptional missing

### ISSUE THREAD

**Issue by Diaaz** [SodiumFRP/sodium-typescript#47]
Hi, I am learning Sodium by converting the sodium-java example from the functional reactive programming book to Typescript and the method filterOptional in Stream is missing. Before I try to implement it myself: is there a reason it is not implemented?

**Comment by clinuxrulz** [comment]
In the TypeScript version they use ```null``` to represent the absent of a value. So the method is ```filterNotNull```. I believe the reason for this is you can signify types that can have absent values in TypeScript's Type System. E.g. the type ```String```, must always have a value, and the type ```String?``` may contain null and the linter will warn if there is no null check before unboxing/casting.

**Comment by dakom** [comment]
Also - there's no inherent Optional type in JS/TS. A popular implementation which I like is Sanctuary's Maybe/Either and you can easily add your own filters with those types, e.g. `filter(m => m.isJust)`

**Comment by Ziriax** [comment]
The problem with typescript is that it does not have extension methods like C#. And you cannot have methods on specialised generic classes. For example, a `filterNotNull` method, when called on a `Stream<T|null>` should return a  `Stream<T>`. But that is impossible to specify in Typescript, unless someone knows how :-)

Therefore I use functions instead of methods:

```
   function filterNotNull<T>(source: Stream<T|null>): Stream<T>
```

I always enable the strictest mode in Typescript, so  null reference exceptions are detected at compile time, saving you from the billion dollar mistake. A helper function like the above greatly helps.  

I tried to make a generalised pipe operator to allow chaining functions in the same way as method calls, but I failed doing so

However it seems the RxJS is also considering using functions instead of methods, and they did make a pipe operator that works, although more clunky than what I had in mind:

https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md

**Comment by clinuxrulz** [comment]
```public filterNotNull<X>(witness: (A a) => X|null): Stream<X>```
And you always pass the identity function for ```witness```. It might confuse the end user though.

**Comment by Ziriax** [comment]
@clinuxrulz That is a very nice trick!

**Comment by dakom** [comment]
Closing this as it appears to be answered with several solutions :)
