### ISSUE TITLE
Fix bug with switchC

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-typescript#53]
discussion @ http://sodium.nz/t/lost-cells-in-switch/267

failing test @ https://github.com/SodiumFRP/sodium-typescript/blob/e4d9f70285bf08e61a05d1757610aeb58d646a50/src/tests/unit/NestedLift.spec.ts#L118

**Comment by dakom** [comment]
In the `switch-fix` branch, I copied the fix @jam40jeff added to the c# version. It's currently unmerged  due to getting a "send was invoked before listeners were registered" error.

Any ideas?

The added code is essentially here: https://github.com/SodiumFRP/sodium-typescript/blob/7484c9fb08ff365a9b66e2134eb653680a71b3ab/src/lib/sodium/Transaction.ts#L57

The line that triggers the error is here: https://github.com/SodiumFRP/sodium-typescript/blob/7484c9fb08ff365a9b66e2134eb653680a71b3ab/src/tests/unit/NestedLift.spec.ts#L135

**Comment by Ziriax** [comment]
This reminds me of https://github.com/SodiumFRP/sodium-typescript/issues/45

**Comment by jam40jeff** [comment]
I believe the problem here is that Cell.apply calls Operational.Value.  The initial value is usually returned later because of the spark stream in Operational.Value.  However, when this is called during the "last" phase of the transaction, it attempts to send the value through right away, likely before the rest of the listeners have had a chance to register themselves.  I'm not sure what can be done to work around this as I don't know enough about the TypeScript implementation.

**Comment by jam40jeff** [comment]
I committed fix for this to the `switch-fix` branch.

**Comment by dakom** [comment]
Merged, thanks @jam40jeff !
